apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-ratelimit-5/test-ratelimit-5-allow-prometheus-metrics.yaml
- test-ratelimit-5/test-ratelimit-5-allow-same-namespace.yaml
- test-ratelimit-5/test-ratelimit-5-deny-all-egress.yaml
- test-ratelimit-5/test-ratelimit-5-deny-all-ingress.yaml
