apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-app-2/test-app-2-allow-prometheus-metrics.yaml
- test-app-2/test-app-2-allow-same-namespace.yaml
- test-app-2/test-app-2-deny-all-egress.yaml
- test-app-2/test-app-2-deny-all-ingress.yaml
- test-app/test-app-allow-prometheus-metrics.yaml
- test-app/test-app-allow-same-namespace.yaml
- test-app/test-app-deny-all-egress.yaml
- test-app/test-app-deny-all-ingress.yaml
- test-variant-c-ns/custom-policy.yaml
- test-variant-c-ns/test-variant-c-ns-allow-prometheus-metrics.yaml
- test-variant-c-ns/test-variant-c-ns-allow-same-namespace.yaml
- test-variant-c-ns/test-variant-c-ns-deny-all-egress.yaml
- test-variant-c-ns/test-variant-c-ns-deny-all-ingress.yaml
