kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
    - ../../test-backup-ns/test-backup-ns-allow-prometheus-metrics.yaml
    - ../../test-backup-ns/test-backup-ns-allow-same-namespace.yaml
    - ../../test-backup-ns/test-backup-ns-deny-all-egress.yaml
    - ../../test-backup-ns/test-backup-ns-deny-all-ingress.yaml
