apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-remove-a/test-remove-a-allow-prometheus-metrics.yaml
- test-remove-a/test-remove-a-allow-same-namespace.yaml
- test-remove-a/test-remove-a-deny-all-egress.yaml
- test-remove-a/test-remove-a-deny-all-ingress.yaml
- test-remove-b/test-remove-b-allow-prometheus-metrics.yaml
- test-remove-b/test-remove-b-allow-same-namespace.yaml
- test-remove-b/test-remove-b-deny-all-egress.yaml
- test-remove-b/test-remove-b-deny-all-ingress.yaml
