apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-state-transitions/test-state-transitions-allow-prometheus-metrics.yaml
- test-state-transitions/test-state-transitions-allow-same-namespace.yaml
- test-state-transitions/test-state-transitions-deny-all-egress.yaml
- test-state-transitions/test-state-transitions-deny-all-ingress.yaml
