kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
    - ../../final-test/final-test-allow-prometheus-metrics.yaml
    - ../../final-test/final-test-allow-same-namespace.yaml
    - ../../final-test/final-test-deny-all-egress.yaml
    - ../../final-test/final-test-deny-all-ingress.yaml
