apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-metrics/test-metrics-allow-prometheus-metrics.yaml
- test-metrics/test-metrics-allow-same-namespace.yaml
- test-metrics/test-metrics-deny-all-egress.yaml
- test-metrics/test-metrics-deny-all-ingress.yaml
