apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-ratelimit-1/test-ratelimit-1-allow-prometheus-metrics.yaml
- test-ratelimit-1/test-ratelimit-1-allow-same-namespace.yaml
- test-ratelimit-1/test-ratelimit-1-deny-all-egress.yaml
- test-ratelimit-1/test-ratelimit-1-deny-all-ingress.yaml
