apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-automerge/test-automerge-allow-prometheus-metrics.yaml
- test-automerge/test-automerge-allow-same-namespace.yaml
- test-automerge/test-automerge-deny-all-egress.yaml
- test-automerge/test-automerge-deny-all-ingress.yaml
