apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- multi-a/multi-a-allow-prometheus-metrics.yaml
- multi-a/multi-a-allow-same-namespace.yaml
- multi-a/multi-a-deny-all-egress.yaml
- multi-a/multi-a-deny-all-ingress.yaml
- multi-b/multi-b-allow-prometheus-metrics.yaml
- multi-b/multi-b-allow-same-namespace.yaml
- multi-b/multi-b-deny-all-egress.yaml
- multi-b/multi-b-deny-all-ingress.yaml
- test-template-changes/test-template-changes-allow-prometheus-metrics.yaml
- test-template-changes/test-template-changes-allow-same-namespace.yaml
- test-template-changes/test-template-changes-deny-all-egress.yaml
- test-template-changes/test-template-changes-deny-all-ingress.yaml
