apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-hfreq/test-hfreq-allow-prometheus-metrics.yaml
- test-hfreq/test-hfreq-allow-same-namespace.yaml
- test-hfreq/test-hfreq-deny-all-egress.yaml
- test-hfreq/test-hfreq-deny-all-ingress.yaml
