kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
    - ../../test-app-2/test-app-2-allow-prometheus-metrics.yaml
    - ../../test-app-2/test-app-2-allow-same-namespace.yaml
    - ../../test-app-2/test-app-2-deny-all-egress.yaml
    - ../../test-app-2/test-app-2-deny-all-ingress.yaml
