apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- multi-a/multi-a-allow-prometheus-metrics.yaml
- multi-a/multi-a-allow-same-namespace.yaml
- multi-a/multi-a-deny-all-egress.yaml
- multi-a/multi-a-deny-all-ingress.yaml
