apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    network-policy.permission-binder.io/template: deny-all-ingress.yaml
    network-policy.permission-binder.io/template-path: networkpolicies/templates/deny-all-ingress.yaml
    network-policy.permission-binder.io/template-version: 1ac0995f31f889591c4e6f05a66c5914f38f6ac6
  creationTimestamp: null
  name: test-app-deny-all-ingress
  namespace: test-app
spec:
  podSelector: {}
  policyTypes:
  - Ingress
