typemeta:
    kind: NetworkPolicy
    apiversion: networking.k8s.io/v1
objectmeta:
    name: test-backup-ns-deny-all-ingress
    generatename: ""
    namespace: test-backup-ns
    selflink: ""
    uid: 2d31f3ef-05ea-4b59-9ff9-712c309d0c52
    resourceversion: "46240947"
    generation: 1
    creationtimestamp: "2025-11-05T16:54:46Z"
    deletiontimestamp: null
    deletiongraceperiodseconds: null
    labels: {}
    annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{"network-policy.permission-binder.io/template":"deny-all-ingress.yaml"},"name":"test-backup-ns-deny-all-ingress","namespace":"test-backup-ns"},"spec":{"ingress":[],"podSelector":{},"policyTypes":["Ingress"]}}
        network-policy.permission-binder.io/template: deny-all-ingress.yaml
    ownerreferences: []
    finalizers: []
    managedfields:
        - manager: kubectl-client-side-apply
          operation: Update
          apiversion: networking.k8s.io/v1
          time: "2025-11-05T16:54:46Z"
          fieldstype: FieldsV1
          fieldsv1:
            raw:
                - 123
                - 34
                - 102
                - 58
                - 109
                - 101
                - 116
                - 97
                - 100
                - 97
                - 116
                - 97
                - 34
                - 58
                - 123
                - 34
                - 102
                - 58
                - 97
                - 110
                - 110
                - 111
                - 116
                - 97
                - 116
                - 105
                - 111
                - 110
                - 115
                - 34
                - 58
                - 123
                - 34
                - 46
                - 34
                - 58
                - 123
                - 125
                - 44
                - 34
                - 102
                - 58
                - 107
                - 117
                - 98
                - 101
                - 99
                - 116
                - 108
                - 46
                - 107
                - 117
                - 98
                - 101
                - 114
                - 110
                - 101
                - 116
                - 101
                - 115
                - 46
                - 105
                - 111
                - 47
                - 108
                - 97
                - 115
                - 116
                - 45
                - 97
                - 112
                - 112
                - 108
                - 105
                - 101
                - 100
                - 45
                - 99
                - 111
                - 110
                - 102
                - 105
                - 103
                - 117
                - 114
                - 97
                - 116
                - 105
                - 111
                - 110
                - 34
                - 58
                - 123
                - 125
                - 44
                - 34
                - 102
                - 58
                - 110
                - 101
                - 116
                - 119
                - 111
                - 114
                - 107
                - 45
                - 112
                - 111
                - 108
                - 105
                - 99
                - 121
                - 46
                - 112
                - 101
                - 114
                - 109
                - 105
                - 115
                - 115
                - 105
                - 111
                - 110
                - 45
                - 98
                - 105
                - 110
                - 100
                - 101
                - 114
                - 46
                - 105
                - 111
                - 47
                - 116
                - 101
                - 109
                - 112
                - 108
                - 97
                - 116
                - 101
                - 34
                - 58
                - 123
                - 125
                - 125
                - 125
                - 44
                - 34
                - 102
                - 58
                - 115
                - 112
                - 101
                - 99
                - 34
                - 58
                - 123
                - 34
                - 102
                - 58
                - 112
                - 111
                - 108
                - 105
                - 99
                - 121
                - 84
                - 121
                - 112
                - 101
                - 115
                - 34
                - 58
                - 123
                - 125
                - 125
                - 125
          subresource: ""
spec:
    podselector:
        matchlabels: {}
        matchexpressions: []
    ingress: []
    egress: []
    policytypes:
        - Ingress
