apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{"network-policy.permission-binder.io/template":"deny-all-ingress.yaml"},"name":"test-backup-ns-deny-all-ingress","namespace":"test-backup-ns"},"spec":{"ingress":[],"podSelector":{},"policyTypes":["Ingress"]}}
        network-policy.permission-binder.io/template: deny-all-ingress.yaml
    creationTimestamp: "2025-11-12T15:25:45Z"
    generation: 1
    managedFields:
        - apiVersion: networking.k8s.io/v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
                f:annotations:
                    .: {}
                    f:kubectl.kubernetes.io/last-applied-configuration: {}
                    f:network-policy.permission-binder.io/template: {}
            f:spec:
                f:policyTypes: {}
          manager: kubectl-client-side-apply
          operation: Update
          time: "2025-11-12T15:25:45Z"
    name: test-backup-ns-deny-all-ingress
    namespace: test-backup-ns
    resourceVersion: "47772916"
    uid: ffee4820-4cb0-49c9-8022-9833f0979041
spec:
    podSelector: {}
    policyTypes:
        - Ingress
