apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    network-policy.permission-binder.io/template: deny-all-ingress.yaml
  name: test-backup-ns-deny-all-ingress
  namespace: test-backup-ns
spec:
  podSelector: {}
  policyTypes:
  - Ingress
