metadata:
  annotations:
    network-policy.permission-binder.io/template: deny-all-ingress.yaml
    network-policy.permission-binder.io/template-path: networkpolicies/templates/deny-all-ingress.yaml
    network-policy.permission-binder.io/template-version: HEAD
  creationTimestamp: "2025-11-12T18:06:52Z"
  generation: 1
  managedFields:
  - apiVersion: networking.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:network-policy.permission-binder.io/template: {}
          f:network-policy.permission-binder.io/template-path: {}
          f:network-policy.permission-binder.io/template-version: {}
      f:spec:
        f:policyTypes: {}
    manager: manager
    operation: Update
    time: "2025-11-12T18:06:52Z"
  name: test-app-2-deny-all-ingress
  namespace: test-app-2
  uid: 77d29b43-b49c-45ea-b5da-583752e2f975
spec:
  podSelector: {}
  policyTypes:
  - Ingress
