apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    network-policy.permission-binder.io/template: deny-all-ingress.yaml
    network-policy.permission-binder.io/template-path: networkpolicies/templates/deny-all-ingress.yaml
    network-policy.permission-binder.io/template-version: HEAD
  name: test-hfreq-deny-all-ingress
  namespace: test-hfreq
spec:
  podSelector: {}
  policyTypes:
  - Ingress
